[package]
name = "hydrate"
version = "0.1.0"
edition = "2021"

[dependencies]
mavlink = {workspace = true}
clap = {workspace = true}
tracing = {workspace = true}
tracing-subscriber = {workspace = true}
