version: '3'
services:
  redis:
    image: redis
    volumes:
      - ./data:/data
    ports:
      - 6379:6379
  web:
    build: ./client
    ports:
      # Container port 8080 will be mapped to port 18080 on the host
      # (You can access the app at http://localhost:18080
      - 18080:8080
