{
 "title": "Altitude",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Packet Lost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as \"Total Messages\" FROM rocket_message WHERE  created_at BETWEEN $__timeFrom()  AND $__timeTo() ;"
    },
    {
     "rawSql": "SELECT sum(packets_lost) as \"Messages Lost\" FROM packet_lost WHERE  created_at BETWEEN $__timeFrom()  AND $__timeTo()"
    },
    { "expression": "$B / ($B + $A)", "type": "math" }
   ]
  },
  {
   "title": "Acceleration m/s2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    rm.created_at,\n    sqrt(\n        power(imu.accelorometer_x, 2) + \n        power(imu.accelorometer_y, 2) + \n        power(imu.accelorometer_z, 2)\n    ) AS imu1_acceleration\nFROM\n    rocket_sensor_imu_1 imu\nJOIN\n    rocket_sensor_message rsm ON imu.rocket_sensor_message_id = rsm.rocket_message_id\nJOIN\n    rocket_message rm ON rsm.rocket_message_id = rm.id\nORDER BY\n    rm.created_at ASC;"
    },
    {
     "rawSql": "SELECT\n    rm.created_at,\n    sqrt(\n        power(imu.delta_velocity_x, 2) + \n        power(imu.delta_velocity_y, 2) + \n        power(imu.delta_velocity_z, 2)\n    ) AS imu2_delta_velocity\nFROM\n    rocket_sensor_imu_2 imu\nJOIN\n    rocket_sensor_message rsm ON imu.rocket_sensor_message_id = rsm.rocket_message_id\nJOIN\n    rocket_message rm ON rsm.rocket_message_id = rm.id\nORDER BY\n    rm.created_at ASC;"
    }
   ]
  },
  {
   "title": "Altitude (m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n    rm.created_at as time,\n    rsa.altitude as air_altitude\nFROM\n    rocket_sensor_air rsa\nJOIN\n    rocket_sensor_message rsm ON rsa.rocket_sensor_message_id = rsm.rocket_message_id\nJOIN\n    rocket_message rm ON rsm.rocket_message_id = rm.id\nORDER BY\n    rm.created_at ASC;"
    },
    {
     "rawSql": "SELECT\n    rm.created_at  as time,\n    rsa.altitude as gps_altitude\nFROM\n    rocket_sensor_gps_pos_2 rsa\nJOIN\n    rocket_sensor_message rsm ON rsa.rocket_sensor_message_id = rsm.rocket_message_id\nJOIN\n    rocket_message rm ON rsm.rocket_message_id = rm.id\nORDER BY\n    rm.created_at ASC;"
    }
   ]
  },
  {
   "title": "Pressure kPa",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n    rm.created_at as time,\n    rsa.pressure_abs / 1000 as pressure\nFROM\n    rocket_sensor_air rsa\nJOIN\n    rocket_sensor_message rsm ON rsa.rocket_sensor_message_id = rsm.rocket_message_id\nJOIN\n    rocket_message rm ON rsm.rocket_message_id = rm.id\nORDER BY\n    rm.created_at ASC;"
    }
   ]
  },
  {
   "title": "IMU Temperature C°",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n    rm.created_at,\n    imu.temperature\nFROM\n    rocket_sensor_imu_2 imu\nJOIN\n    rocket_sensor_message rsm ON imu.rocket_sensor_message_id = rsm.rocket_message_id\nJOIN\n    rocket_message rm ON rsm.rocket_message_id = rm.id\nORDER BY\n    rm.created_at ASC;\n"
    }
   ]
  }
 ]
}