version: "3.1"

services:
    db:
        image: timescale/timescaledb:latest-pg16
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
            interval: 1s
            timeout: 1s
            retries: 25

    db-setup:
        build:
            context: ./db
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - ./db/dump:/app/dump
        command: ["npm", "run", "bootstrap"]
        # Keep alive
        # command: ["tail", "-f", "/dev/null"]
        # tty: true
        # stdin_open: true
        environment:
            DATABASE_URL: postgres://postgres:postgres@db:5432/postgres

    hasura:
        image: hasura/graphql-engine:latest
        ports:
            - "8080:8080"
        depends_on:
            db-setup:
                condition: service_completed_successfully
        environment:
            HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
            HASURA_GRAPHQL_ADMIN_SECRET: uorocketry
            HASURA_GRAPHQL_LOG_LEVEL: warn
            HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
            HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
            interval: 1s
            timeout: 1s
            retries: 25
