site_name: RGS Docs
site_description: Rocket Ground Station documentation
site_url: https://uorocketry.github.io/rgs
repo_url: https://github.com/uorocketry/rgs
repo_name: uorocketry/rgs

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Guide:
      - Overview: guide/index.md
      - Architecture: guide/architecture.md
      - Requirements:
          - Development environment: guide/requirements/development-environment.md
          - Docker: guide/requirements/docker.md
          - Bun: guide/requirements/bun.md
          - Rust: guide/requirements/rust.md
      - Hands-on:
          - Modify the database: guide/hands-on/modifying-the-database.md
          - Altitude widget: guide/hands-on/altitude-widget.md
  - Services:
      - Sergw: sergw/index.md
      - Web: web/index.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - tables
  - footnotes

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/uorocketry


