[package]
name = "hydra_provider"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
messages = { git = "https://github.com/uorocketry/hydra", branch = "serialization" }
serialport = "4.2.0"
postcard = "1.0.2"
serde_json = "1.0.91"
clap = { version = "4.0.29", features = ["derive", "env"] }
