[package]
name = "hydra_provider"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
messages = { git = "https://github.com/uorocketry/hydra", branch = "serialization" }
tokio-serial = "5.4.1"
postcard = "1.0.2"
serde_json = "1.0.91"
clap = { version = "4.0.29", features = ["derive", "env"] }
anyhow = { version = "1.0.68", features = ["backtrace"] }
log = "0.4.17"
env_logger = "0.10.0"
tokio = { version = "1", features = ["full"] }