Help("""
Invocation:

    Make:
    $ python scons-local-2.5.1/scons.py

    Clean:
    $ python scons.py -c

    Quiet:
    $ scons -Q

""")

import os

link_libs = 'LabJackM'
ccflags = '-g -Wall'
env = Environment(CCFLAGS = ccflags)

examples_src = Split("""
    change_directory.cpp
    delete_file.cpp
    get_disk_info.cpp
    list_directory.cpp
    print_working_directory.cpp
    read_file.cpp
""")

# Make
for example in examples_src:
    lib = env.Program(target = os.path.splitext(example)[0], source = example, LIBS = link_libs)


