Help("""
Invocation:

    Make:
    $ python scons-local-2.5.1/scons.py

    Clean:
    $ python scons.py -c

    Quiet:
    $ scons -Q

""")

import os

link_libs = 'LabJackM'
ccflags = '-g -Wall'
env = Environment(CCFLAGS = ccflags)

examples_src = Split("""
    eAddresses.c
    eNames.c
    eReadAddress.c
    eReadAddresses.c
    eReadName.c
    eReadNames.c
    eWriteAddress.c
    eWriteAddresses.c
    eWriteName.c
    eWriteNames.c
    write_read_loop_with_config.c
""")

# Make
for example in examples_src:
    lib = env.Program(target = os.path.splitext(example)[0], source = example, LIBS = link_libs)


