Help("""
Invocation:

    Make:
    $ python scons-local-2.5.1/scons.py

    Clean:
    $ python scons.py -c

    Quiet:
    $ scons -Q

""")

import os

link_libs = 'LabJackM'
ccflags = '-g -Wall'
env = Environment(CCFLAGS = ccflags)

examples_src = Split("""
    auto_reconnect_test.c
    c-r_speed_test.c
    externally_clocked_stream_test.c
    stream_burst_test.c
    system_reboot_test.c
    write_read_loop_with_config_speed_test_eNames.c
""")

# Make
for example in examples_src:
    lib = env.Program(target = os.path.splitext(example)[0], source = example, LIBS = link_libs)


