[package]
name = "virtual-serial"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["derive"] }
nix = { version = "0.28", features = ["term"] }
libc = "0.2"
anyhow = "1"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }


