[package]
name = "sergw"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
messages = { workspace = true }
mavlink = {workspace = true}
postcard = "1"
serialport = "4"
serde_json = "1"
serde = "1"