[package]
name = "sergw"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
mavlink = {workspace = true}
postcard = { workspace = true }
serialport = "4"
serde_json = { workspace = true }
serde = { workspace = true }