[package]
name = "tile_provider"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
r2d2 = "0.8"
r2d2_sqlite = "0.22"
rusqlite = "0.29"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
dashmap = "5.0"
