// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeployDrogue } from "./DeployDrogue";
import type { DeployMain } from "./DeployMain";

export type CommandData = { DeployDrogue: DeployDrogue } | { DeployMain: DeployMain };