// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface EkfNav2 {
    /** Latitude, Longitude, Altitude above Mean Sea Level. */
    position: Array<number>,
    undulation: number,
    position_std_dev: Array<number>,
    status: number,
}