// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface EkfNav1 {
    time_stamp: number,
    /** North, East, Down velocity in m.s^-1. */
    velocity: Array<number>,
    velocity_std_dev: Array<number>,
}