// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GpsPos2 { latitudeAccuracy: number, longitudeAccuracy: number, altitudeAccuracy: number, numSvUsed: number, baseStationId: number, differentialAge: number, }