// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GpsPos1 { timeStamp: number, status: number, timeOfWeek: number, latitude: number, longitude: number, altitude: number, undulation: number, }