// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Imu1 {
    time_stamp: number,
    status: number,
    /** X, Y, Z accelerometers in m.s^-2.*/
    accelerometers: Array<number>,
    /** X, Y, Z delta angle in rad.s^-1. */
    gyroscopes: Array<number>,
}