// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LinkStatus { rssi: number | null, remrssi: number | null, txbuf: number | null, noise: number | null, remnoise: number | null, rxerrors: number | null, fixed: number | null, recent_error_rate: number, missed_messages: number, connected: boolean, timestamp: bigint, }