// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkStatus } from "./LinkStatus";
import type { Message } from "./Message";

export type ProcessedMessage = { RocketMessage: Message } | { LinkStatus: LinkStatus };